name: Build Servers + Mihomo YAML

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run script (generate servers.txt)
        run: python script.py

      # =========================
      # Convert using Subconverter (Docker)
      # =========================
      - name: Convert to Mihomo YAML
        run: |
          docker run --rm \
            -v $PWD:/data \
            ghcr.io/tindy2013/subconverter:latest \
            -i "https://raw.githubusercontent.com/miladsa740/mi404/refs/heads/main/servers.txt" \
            -o /data/flclashmi.yaml

      # =========================
      # Commit
      # =========================
      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add servers.txt flclashmi.yaml

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update servers + Mihomo YAML"
            git push origin HEAD:main
          fi
