name: Build Servers + Mihomo YAML

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script (generate servers.txt)
        run: python script.py

      # =========================
      # Install Subconverter manually
      # =========================
      - name: Install Subconverter
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libcurl4-openssl-dev libssl-dev zlib1g-dev

          git clone https://github.com/tindy2013/subconverter.git
          cd subconverter
          mkdir build && cd build
          cmake ..
          make -j2

      # =========================
      # Convert to Mihomo YAML
      # =========================
      - name: Generate flclashmi.yaml
        run: |
          cd subconverter/build

          ./subconverter \
            -i "https://raw.githubusercontent.com/miladsa740/mi404/refs/heads/main/servers.txt" \
            -o ../../flclashmi.yaml

      # =========================
      # Commit results
      # =========================
      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          git add servers.txt flclashmi.yaml

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update servers + Mihomo YAML"
            git push origin HEAD:main
          fi
